# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-08 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imglist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imglist',
            name='imgName',
        ),
    ]
