# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addresslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uId', models.CharField(max_length=300, null=True)),
                ('province', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=300, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('detailedddressd', models.CharField(max_length=300, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'addresslist',
            },
        ),
        migrations.CreateModel(
            name='userlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uId', models.CharField(max_length=300, null=True)),
                ('telphone', models.CharField(max_length=11, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userlist',
            },
        ),
    ]
