# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodlist', '0002_auto_20190530_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodlist',
            name='goodImageId',
        ),
        migrations.AlterField(
            model_name='goodlist',
            name='platform',
            field=models.IntegerField(default=0),
        ),
    ]
