# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodlist', '0003_auto_20190530_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodlist',
            name='XLLinventoryNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goodlist',
            name='goodDesc',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
