# Generated by Django 2.2.2 on 2019-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodlist', '0007_goodlist_goodcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodlist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
