# Generated by Django 2.2.2 on 2019-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodlist', '0008_auto_20190619_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
