# Generated by Django 2.2.2 on 2019-06-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodlist', '0009_auto_20190619_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodlist',
            old_name='platform',
            new_name='isCheck',
        ),
    ]
